apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
- role: control-plane
  image: kindest/node:v1.32.2
- role: worker
  image: kindest/node:v1.32.2
  extraPortMappings:
  - hostPort: 8080
    containerPort: 8080
    protocol: TCP
